# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nznUp38r235otxrHTVufzASAoVYoSsUR

IMPORT LIBRARIES AND LOADING DATA
"""

# Commented out IPython magic to ensure Python compatibility.
#import Libraries
import pandas as pd
import numpy as np
import seaborn as sns
# %matplotlib inline
#loading data
Data=pd.read_csv("BrandDetails.csv")
Data.head()

"""PROBLEM #1: Which industry has the maximum brands whose Brand_revenue>80 million"""

#SOLUTION 1
Data1=Data[Data['Brand_Revenue']>80].groupby(['Industry'],as_index=False)['Brand'].count()
Data1[Data1['Brand']==Data1['Brand'].max()]

"""PROBLEM#2: List the companies whose company_Advertising budget is <3 but Brand_value is >20"""

#SOLUTION 2
Data2=Data[(Data['Company_Advertising']<3)&(Data['Brand_Value']>20)]['Brand']
Data2

"""PROBLEM#3: top 5 technology brand that showed maximum positive jump in their position (use change_LastYr)"""

#SOLUTION 3
Data3=Data[Data['Industry']=="Technology"].nlargest(5,['Change_LastYr'])["Brand"].reset_index()
Data3

"""PROBLEM#4: FIND OUT THE AVERAGE BRAND_REVENUE BY INDUSTRY"""

#SOLUTION 4(Described using pie chart)
Data4=Data.groupby(['Industry'])['Brand_Revenue'].mean()
Data4
Data4.plot(kind='pie',figsize=(8,8))